#!D:\Obulesu_gajula_onedrive\OneDrive - Course5 Intelligence Pvt Ltd\Desktop\ML\demo-ML\Scripts\python.exe

import sys
from aws_ecs_services import aws_ecs_services

if __name__ == "__main__":
    sys.exit(aws_ecs_services.main())
